(function(i) {
    var i = i || [];
    var o = [];
    var t = new Uint16Array(9999);
    var p = 0;
    t[p + 1] += 7;
    p += 1;
    t[p - 1] += t[p] * 10;
    t[p] = 0;
    p -= 1;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p] -= 11;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 8;
        t[p] += 1
    };
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 6;
    p += 1;
    t[p - 1] += t[p] * 9;
    t[p] = 0;
    p -= 1;
    o.push(t[p]);
    t[p + 1] -= 4;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 4;
        t[p] += 1
    };
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p] += 13;
    o.push(t[p]);
    t[p] -= 9;
    o.push(t[p]);
    t[p] -= 3;
    o.push(t[p]);
    t[p] += 3;
    o.push(t[p]);
    t[p] -= 6;
    o.push(t[p]);
    t[p] -= 2;
    o.push(t[p]);
    t[p + 1] += 3;
    p += 1;
    t[p - 1] += t[p] * 6;
    t[p] = 0;
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p] -= 11;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p] -= 1;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 9;
        t[p] += 1
    };
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 7;
    p += 1;
    t[p - 1] += t[p] * 7;
    t[p] = 0;
    t[p - 1] += 2;
    p -= 1;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p] -= 6;
    o.push(t[p]);
    t[p] += 1;
    o.push(t[p]);
    t[p + 1] -= 3;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 5;
        t[p] += 1
    };
    p -= 1;
    o.push(t[p]);
    t[p] += 8;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 9;
        t[p] += 1
    };
    p -= 1;
    o.push(t[p]);
    t[p] += 13;
    o.push(t[p]);
    o.push(t[p]);
    o.push(t[p]);
    t[p] -= 13;
    o.push(t[p]);
    t[p + 1] += 5;
    p += 1;
    t[p - 1] += t[p] * 7;
    t[p] = 0;
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p] += 1;
    o.push(t[p]);
    o.push(t[p]);
    t[p + 1] += 4;
    p += 1;
    t[p - 1] += t[p] * 4;
    t[p] = 0;
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p] -= 14;
    o.push(t[p]);
    t[p + 1] -= 6;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 10;
        t[p] += 1
    };
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 6;
    p += 1;
    t[p - 1] += t[p] * 10;
    t[p] = 0;
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p] += 9;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p + 1] -= 3;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 5;
        t[p] += 1
    };
    p -= 1;
    o.push(t[p]);
    t[p] += 13;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 10;
        t[p] += 1
    };
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 6;
    p += 1;
    t[p - 1] += t[p] * 6;
    t[p] = 0;
    t[p - 1] += 2;
    p -= 1;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p] -= 11;
    o.push(t[p]);
    t[p] += 6;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 8;
        t[p] += 1
    };
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 6;
    p += 1;
    t[p - 1] += t[p] * 9;
    t[p] = 0;
    t[p - 1] -= 2;
    p -= 1;
    o.push(t[p]);
    t[p] -= 5;
    o.push(t[p]);
    t[p + 1] -= 6;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 8;
        t[p] += 1
    };
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 6;
    p += 1;
    t[p - 1] += t[p] * 9;
    t[p] = 0;
    p -= 1;
    o.push(t[p]);
    t[p + 1] -= 4;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 4;
        t[p] += 1
    };
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p] += 13;
    o.push(t[p]);
    t[p] -= 9;
    o.push(t[p]);
    t[p] -= 3;
    o.push(t[p]);
    t[p + 1] += 3;
    p += 1;
    t[p - 1] += t[p] * 6;
    t[p] = 0;
    t[p - 1] += 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 6;
        t[p] += 1
    };
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] -= 5;
    p += 1;
    while (t[p] != 0) {
        t[p - 1] -= 5;
        t[p] += 1
    };
    t[p - 1] -= 1;
    p -= 1;
    o.push(t[p]);
    t[p + 1] += 7;
    p += 1;
    t[p - 1] += t[p] * 13;
    t[p] = 0;
    t[p - 1] += 2;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 14;
    t[p] = 0;
    t[p - 1] += 3;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 14;
    t[p] = 0;
    t[p - 1] += 3;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 13;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 11;
    p += 3;
    t[p - 1] += t[p] * 11;
    t[p] = 0;
    t[p - 1] -= 2;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 14;
    t[p] = 0;
    t[p - 1] += 3;
    t[p + 3] += 5;
    p += 3;
    t[p - 1] += t[p] * 19;
    t[p] = 0;
    t[p + 3] += 10;
    p += 3;
    t[p - 1] += t[p] * 10;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 13;
    t[p] = 0;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 14;
    t[p] = 0;
    t[p - 1] += 4;
    t[p + 3] += 5;
    p += 3;
    t[p - 1] += t[p] * 19;
    t[p] = 0;
    t[p + 3] += 10;
    p += 3;
    t[p - 1] += t[p] * 10;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 13;
    t[p] = 0;
    t[p - 1] += 5;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 12;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 13;
    t[p] = 0;
    t[p - 1] += 4;
    t[p + 3] += 8;
    p += 3;
    t[p - 1] += t[p] * 12;
    t[p] = 0;
    t[p - 1] += 2;
    t[p + 3] += 11;
    p += 3;
    t[p - 1] += t[p] * 11;
    t[p] = 0;
    t[p - 1] += 2;
    t[p + 3] += 7;
    p += 3;
    t[p - 1] += t[p] * 10;
    t[p] = 0;
    t[p + 3] += 7;
    p += 3;
    t[p - 1] += t[p] * 12;
    t[p] = 0;
    t[p + 3] += 6;
    p += 3;
    t[p - 1] += t[p] * 11;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 6;
    p += 3;
    t[p - 1] += t[p] * 11;
    t[p] = 0;
    t[p - 1] += 1;
    t[p + 3] += 6;
    p += 3;
    t[p - 1] += t[p] * 11;
    t[p] = 0;
    t[p + 1] += 1;
    console.log(t)
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    t[p - 2] += 1;
    p -= 3;
    t[p] = (i.length < 1 ? 0 : i.shift());
    p -= 1;
    while (t[p] != 0) {
        while (t[p] != 0) {
            t[p] -= 1;
            t[p + 1] -= 1
        };
        p += 1;
        while (t[p] != 0) {
            t[p + 1] -= 1;
            t[p] = 0
        };
        p += 1;
        t[p + 3] += t[p];
        t[p] = 0;
        p += 1
    };
    t[p] += 4;
    t[p + 1] += t[p] * 5;
    t[p] = 0;
    t[p] += 1;
    t[p + 1] += 2;
    p += 1;
    while (t[p] != 0) {
        t[p] -= 1;
        t[p + 1] -= 1
    };
    p += 1;
    console.log(t)
    while (t[p] != 0) {
        t[p - 2] -= 1;
        t[p] = 0;
        t[p] += 10;
        o.push(t[p]);
        t[p + 1] += 6;
        p += 1;
        t[p - 1] += t[p] * 10;
        t[p] = 0;
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 6;
        p += 1;
        t[p - 1] += t[p] * 6;
        t[p] = 0;
        t[p - 1] += 2;
        p -= 1;
        o.push(t[p]);
        t[p] -= 11;
        o.push(t[p]);
        t[p] += 6;
        o.push(t[p]);
        t[p + 1] -= 7;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 10;
            t[p] += 1
        };
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 7;
        p += 1;
        t[p - 1] += t[p] * 12;
        t[p] = 0;
        t[p - 1] += 2;
        p -= 1;
        o.push(t[p]);
        t[p + 1] -= 4;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 4;
            t[p] += 1
        };
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p] += 13;
        o.push(t[p]);
        t[p] -= 9;
        o.push(t[p]);
        t[p] -= 3;
        o.push(t[p]);
        t[p] += 3;
        o.push(t[p]);
        t[p] -= 6;
        o.push(t[p]);
        t[p] -= 2;
        o.push(t[p]);
        t[p + 1] += 3;
        p += 1;
        t[p - 1] += t[p] * 6;
        t[p] = 0;
        t[p - 1] += 1;
        p -= 1;
        o.push(t[p]);
        t[p] -= 11;
        o.push(t[p]);
        t[p] += 6;
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p + 1] -= 6;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 13;
            t[p] += 1
        };
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 7;
        p += 1;
        t[p - 1] += t[p] * 10;
        t[p] = 0;
        p -= 1;
        o.push(t[p]);
        t[p] -= 5;
        o.push(t[p]);
        t[p] += 8;
        o.push(t[p]);
        t[p] += 3;
        o.push(t[p]);
        t[p] -= 7;
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p + 1] -= 6;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 11;
            t[p] += 1
        };
        t[p - 1] -= 2;
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 6;
        p += 1;
        t[p - 1] += t[p] * 6;
        t[p] = 0;
        p -= 1;
        o.push(t[p]);
        t[p] -= 10;
        o.push(t[p]);
        t[p] = 0
    };
    console.log(t)
    p -= 2;
    while (t[p] != 0) {
        t[p] = 0;
        t[p] += 10;
        o.push(t[p]);
        t[p + 1] += 6;
        p += 1;
        t[p - 1] += t[p] * 10;
        t[p] = 0;
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 6;
        p += 1;
        t[p - 1] += t[p] * 6;
        t[p] = 0;
        t[p - 1] += 2;
        p -= 1;
        o.push(t[p]);
        t[p] -= 11;
        o.push(t[p]);
        t[p] += 6;
        o.push(t[p]);
        t[p + 1] -= 7;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 10;
            t[p] += 1
        };
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 7;
        p += 1;
        t[p - 1] += t[p] * 12;
        t[p] = 0;
        t[p - 1] += 2;
        p -= 1;
        o.push(t[p]);
        t[p + 1] -= 4;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 4;
            t[p] += 1
        };
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p] += 13;
        o.push(t[p]);
        t[p] -= 9;
        o.push(t[p]);
        t[p] -= 3;
        o.push(t[p]);
        t[p] += 3;
        o.push(t[p]);
        t[p] -= 6;
        o.push(t[p]);
        t[p] -= 2;
        o.push(t[p]);
        t[p + 1] += 3;
        p += 1;
        t[p - 1] += t[p] * 6;
        t[p] = 0;
        t[p - 1] += 1;
        p -= 1;
        o.push(t[p]);
        t[p] -= 11;
        o.push(t[p]);
        t[p] += 6;
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p + 1] -= 6;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 13;
            t[p] += 1
        };
        p -= 1;
        o.push(t[p]);
        t[p + 1] += 7;
        p += 1;
        t[p - 1] += t[p] * 12;
        t[p] = 0;
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p] += 2;
        o.push(t[p]);
        t[p + 1] -= 3;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 6;
            t[p] += 1
        };
        p -= 1;
        o.push(t[p]);
        o.push(t[p]);
        t[p] += 2;
        o.push(t[p]);
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p] += 1;
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p + 1] -= 6;
        p += 1;
        while (t[p] != 0) {
            t[p - 1] -= 11;
            t[p] += 1
        };
        t[p - 1] -= 1;
        p -= 1;
        o.push(t[p]);
        t[p] -= 1;
        o.push(t[p]);
        t[p + 1] += 5;
        p += 1;
        t[p - 1] += t[p] * 5;
        t[p] = 0;
        t[p - 1] += 1;
        p -= 1;
        o.push(t[p]);
        t[p] += 10;
        o.push(t[p]);
        t[p] = 0
    };
    return o.map(x => String.fromCharCode(x)).join('');
})(new Uint8Array())